<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Penjamin
 * @subpackage View
 * @filesource dataPenjamin.phtml
 */
?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa fa-edit active"></i> <a href="<?php echo URL ?>penjamin">Data  Penjamin </a>
                </li>
                <?php if($_SESSION['level']==='superadmin'):?>
                <li>
                    <i class="fa fa-table active"></i> Data All Penjamin   
                </li>
                <?php endif;?>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Penjamin Costumer  </h3>
        </div>
        <div class="box-body" > 
            <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                <thead>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-2">Alamat</th>
                        <th class="col-sm-2">Pekerjaan</th>
                        <th class="col-sm-2" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $val['nik_costumer'] ?></td>
                            <td><?php echo $val['nama'] ?></td>
                            <td><?php echo $val['alamat'] ?></td>
                            <td><?php echo $val['pekerjaan'] ?></td>

                            <td align="center">

                                    <a href="<?php echo URL . 'penjamin/index/detail/' . $val['nik_costumer']; ?>"> <i class="fa fa-edit"></i>DETAIL </a>                              
                                <?php if($_SESSION['level']==='superadmin'):?>
                                    &nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'penjamin/index/edit/' . $val['nik_costumer']; ?>"> <i class="fa fa-edit"></i>EDIT </a>
                                    &nbsp;&nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'penjamin/index/delete/' . $val['nik_costumer']; ?>"> <i class="fa fa-trash-o"></i>DELETE </a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
                <tfoot>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-2">Alamat</th>
                        <th class="col-sm-2">Pekerjaan</th>
                        <th class="col-sm-2">Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>