<?php $id = $awal . '/' . $akhir; ?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/kartupiutang">Kartu Piutang</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/kas">Buku Besar Penerimaan Kas</a>
                </li>
                <li>
                    Cetak Buku Besar Perimaan Piutang
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i>Cetak Buku Besar Perimaan Piutang</h3>
                </div>

                <div class="panel-body">
                    <br/>
                    <table width="80%" align="center"  >
                        <thead>
                            <tr>
                                <td rowspan="1" align="center" width="20%">
                                    <img src="<?php echo URL ?>public/images/logo.png" height="80">
                                </td>
                                <td  align="left" colspan="3"><strong><font size="4">PT MITRA DANA PUTRA UTAMA FINANCE LAMPUNG</font></strong><br/><font size="3"><b>Buku Besar Piutang </b></font><br/><b>Per Tanggal </b><?php echo date('d/m/Y',  strtotime( $awal)) . ' - ' . date('d/m/Y',  strtotime($akhir)); ?></td>
                            </tr>
                            <tr>
                                <td colspan="4"><hr></td>
                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="4">
                                    <table width="100%"   border='1' cellpading="1" cellspacing="1">
                                        <tr>
                                            <th>No</th>
                                            <th widht="10%">No Kontrak</th>
                                            <th widht="15%" >Nama Costumer</th>
                                            <th widht="20%" style="text-align: right">Debit</th>
                                            <th widht="15%" style="text-align: center">Kredit</th>
                                            <th widht="20%" style="text-align: right">Saldo</th>
                                        </tr>

                                        <tr>
                                            <?php $saldo = 0; ?>    
                                            <?php $no = 0; ?>     
                                            <?php $totalDebit = 0; ?>    
                                            <?php $totalKredit = 0; ?>   
                                            <?php $ic = 0; ?>
                                            <?php foreach ( $dataCetak as $key => $val ):$no++ ?>
                                                <?php $i = $key - 1; ?>
                                                <?php $saldo +=isFloatNum( $dataCetak[ $key ][ 'debit' ] ); ?>
                                                <td><?php echo $no ?></td>
                                                <td><?php echo $val[ 'no_kontrak' ] ?></td>
                                                <td><?php echo $val[ 'nama' ] ?></td>
                                                <td style="text-align: right"><?php echo $val[ 'debit' ] ?></td>
                                                <td style="text-align: right"><?php echo $val[ 'kredit' ] ?></td>
                                                <?php if ( $key == '0' ): ?>
                                                <td style="text-align: right"><?php echo $val[ 'saldo' ] ?></td>
                                                <?php else : ?>
                                                <td style="text-align: right"><?php echo rupiah( $saldo ) ?></td>
                                                <?php endif; ?>
                                                <?php $totalDebit += isFloatNum( $val[ 'debit' ] ); ?>
                                                <?php $totalKredit += isFloatNum( $val[ 'saldo' ] ); ?>

                                            </tr>
                                        <?php endforeach; ?>
                                        </tr>
                                        <?php /*
                                        <tr>
                                            <td colspan="5" align='right'> Total Saldo &nbsp;</td>
                                            <td><?php echo $saldo;?></td>
                                        </tr>   
                                         * 
                                         */?> 
                                    </table>

                                </td>
                            </tr>
                            <tr>
                                <td colspan="4"><hr></td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <table width="100%">

                                        <tr align="center">
                                            <td width="50%">Akuntasi</td>
                                            <td widht='50%'>Pimpinan</td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" height="90">&nbsp;</td>
                                        </tr>
                                        <tr align="center">
                                            <td><?php echo $_SESSION[ 'dataLogin' ][ 'realname' ]; ?></td>
                                            <td><?php echo $_SESSION[ 'dataLogin' ][ 'kepala_cabang' ]; ?></td>
                                        </tr >
                                    </table>
                                </td>
                            </tr>
                            <?php if($_SESSION['level']==='akuntan'):?>
                                <tr valign="bottom">
                                    <td colspan="4" align="right" height="50"><a  onclick="cetak()" class="btn btn-primary" role="button">Cetak</a></td>
                                </tr>
                            <?php endif;?>    
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var cetak = function () {
        var params = [
            'height=' + screen.height,
            'width=' + screen.width / 2,
            'fullscreen=yes' // only works in IE, but here for completeness
        ].join(',');
        window.open('<?php echo URL . 'laporan/index/cetakPiutang/' . $id; ?>');// 'toolbar=no, scrollbars=no, resizable=no,fullscreen=1');
    };
</script>