<script>
    window.print();
    window.onfocus = function(){
        
            window.close();
        
        
    };
</script>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i>Cetak Penerimaan Kas</h3>
                </div>
                
                <div class="panel-body">
                    <br/>
                    <table width="100%" align="center"  >
                        <thead>
                            <tr>
                                <td rowspan="1" align="center" width="20%">
                                    <img src="<?php echo URL?>public/images/logo.png" height="80">
                                </td>
                                <td  align="left" colspan="3"><strong>PT MITRA DANA PUTRA UTAMA FINANCE LAMPUNG</strong><br/>Buku Besar Penerimaan Kas <br/>Pertanggal <?php echo $awal .'/'.$akhir;?></td>
                            </tr>
                            <tr>
                                <td colspan="4"><hr></td>
                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="4">
                                        <table width="100%" >
                                        <tr>
                                        <td width="3%">No</td>
                                        <td width="10%">No Kontrak</td>
                                        <td  width="10%">Nama Costumer</td>
                                        <td  width="5%" align="center">Angsuran Ke</td>
                                        <td width="7%">Angsuran</td>
                                        <td  width="7%">Denda</td>
                                        <td  width="7%">Bya Tagih</td>
                                        <td  width="5%">BO</td>
                                        <td width="7%">Discount</td>
                                        <td width="7%">Total</td>
                                        <td width="7%">No Kwitansi</td>
                                        <td width="7%">Tgl Bayar</td>
                                        <td width="7%">Keterangan</td>
                                        </tr>
                                        
                                            <tr>
                                        <?php  $no=0;?>     
                                        <?php $totalangsuran = 0;?>    
                                        <?php $totaldenda = 0;?>    
                                        <?php $totalbiayatagh = 0;?>    
                                        <?php $totaldicount = 0;?>    
                                        <?php $totalbayar = 0;?>    
                                        <?php foreach ($dataCetak as $key=>$val):$no++?>
                                            <?php // if($key['lama_angsuran'])?>
                                            <td><?php echo $no?></td>
                                            <td><?php echo $val['no_kontrak']?></td>
                                            <td><?php echo $val['nama']?></td>
                                            <td align="center"><?php echo $val['angsuran_ke']?></td>
                                            <td><?php echo $val['angsuran']?></td>
                                            <td><?php echo $val['denda']?></td>
                                            <td><?php echo $val['biaya_tagih']?></td>
                                            <td><?php echo $val['bo']?></td>
                                            <td><?php echo $val['discount']?></td>
                                            <td><?php echo $val['total']?></td>
                                            <td><?php echo $val['no_kwitansi']?></td>
                                            <td><?php echo $val['tgl_bayar']?></td>
                                            <td><?php echo $val['keterangan']?></td>
                                            <?php $totalangsuran += isFloatNum($val['angsuran']);?>
                                            <?php $totaldenda += isFloatNum($val['denda']);?>
                                            <?php $totalbiayatagh += isFloatNum($val['biaya_tagih']);?>
                                            <?php $totaldicount += isFloatNum($val['discount']);?>
                                            <?php $totalbayar += isFloatNum($val['total']);?>
                                        </tr>
                                        <?php endforeach;?>
                                        <?php #$sisa = 0;?>
                                        <?php #$sisa = isFloatNum($dataCetak[0]['nilai_pinjaman']) - $total  ?>
                                        <tr>
                                            <td colspan="3"> Sub Total &nbsp;</td>
                                            <td>&nbsp;</td>
                                            <td><?php echo  !empty($totalangsuran) ? rupiah($totalangsuran) : '0,00'?></td>
                                            <td><?php echo  !empty($totaldenda) ? rupiah($totaldenda) : '0,00'?></td>
                                            <td><?php echo  !empty($totalbiayatagh) ? rupiah($totalbiayatagh) : '0,00'?></td>
                                            <td>&nbsp;</td>
                                            <td><?php echo !empty($totaldicount) ? rupiah($totaldicount) : '0,00'?></td>
                                            <td><?php echo  !empty($totalbayar) ? rupiah($totalbayar) : '0,00'?></td>
                                            <td colspan="2" align="right">&nbsp;</td>
                                            <td>&nbsp;</td>
                                        </tr>                                
                                    </table>
                                    
                                </td>
                            </tr>
                             <tr>
                                <td colspan="4"><hr></td>
                            </tr>
                                                        
                           
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
