<?php $id= $awal.'/'.$akhir;?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/kartupiutang">Kartu Piutang</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/piutang">Buku Besar Piutang</a>
                </li>
                <li>
                    Cetak Penerimaan Kas
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i>Cetak Penerimaan Kas</h3>
                </div>
                
                <div class="panel-body">
                    <br/>
                    <table width="100%" align="center"  >
                        <thead>
                            <tr>
                                <td rowspan="1" align="center" width="20%">
                                    <img src="<?php echo URL?>public/images/logo.png" height="80">
                                </td>
                                <td  align="left" colspan="2"><strong><font size="4">PT MITRA DANA PUTRA UTAMA FINANCE LAMPUNG</font></strong><br/><b><font size="2">Kartu Piutang</font></b> <br/><b>Per tanggal</b> : &nbsp; <?php echo date('d/m/Y',  strtotime($akhir)) .'/'.date('d/m/Y',  strtotime($awal));;?></td>
                            </tr>
                            <tr>
                                <td colspan="4"><hr></td>
                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="4">
                                        <table width="100%"  >
                                        <tr>
                                        <td width="3%">No</td>
                                        <td width="8%">No Kontrak</td>
                                        <td  width="8%">Nama Costumer</td>
                                        <td  width="5%" align="center">Angsuran Ke</td>
                                        <td width="7%" style="text-align: right">Angsuran</td>
                                        <td  width="7%" style="text-align: right">Denda</td>
                                        <td  width="7%" style="text-align: right">Bya Tagih</td>
                                        <td  width="7%" style="text-align: center">BO</td>
                                        <td width="7%" style="text-align: right">Discount</td>
                                        <td width="7%" style="text-align: right">Total</td>
                                        <td width="7%">No Kwitansi</td>
                                        <td width="7%">Tgl Bayar</td>
                                        <td width="7%">Keterangan</td>
                                        </tr>
                                        <tr>
                                            <td colspan="10"><hr></td>
                                        </tr>
                                        <tr>
                                        <?php  $no=0;?>     
                                        <?php $totalangsuran = 0;?>    
                                        <?php $totaldenda = 0;?>    
                                        <?php $totalbiayatagh = 0;?>    
                                        <?php $totaldicount = 0;?>    
                                        <?php $totalbayar = 0;?>    
                                        <?php foreach ($dataCetak as $key=>$val):$no++?>
                                            <?php // if($key['lama_angsuran'])?>
                                            <td><?php echo $no?></td>
                                            <td><?php echo $val['no_kontrak']?></td>
                                            <td><?php echo $val['nama']?></td>
                                            <td align="center"><?php echo $val['angsuran_ke']?></td>
                                            <td style="text-align: right"><?php echo $val['angsuran']?></td>
                                            <td style="text-align: right"><?php echo $val['denda']?></td>
                                            <td style="text-align: right"><?php echo $val['biaya_tagih']?></td>
                                            <td style="text-align: center"><?php echo $val['bo']?></td>
                                            <td style="text-align: right"><?php echo $val['discount']?></td>
                                            <td style="text-align: right"><?php echo $val['total']?></td>
                                            <td><?php echo $val['no_kwitansi']?></td>
                                            <td><?php echo date('d/m/Y',  strtotime($val['tgl_bayar']));?></td>
                                            <td><?php echo $val['keterangan']?></td>
                                            <?php $totalangsuran += isFloatNum($val['angsuran']);?>
                                            <?php $totaldenda += isFloatNum($val['denda']);?>
                                            <?php $totalbiayatagh += isFloatNum($val['biaya_tagih']);?>
                                            <?php $totaldicount += isFloatNum($val['discount']);?>
                                            <?php $totalbayar += isFloatNum($val['total']);?>
                                        </tr>
                                        <?php endforeach;?>
                                        <?php #$sisa = 0;?>
                                        <?php #$sisa = isFloatNum($dataCetak[0]['nilai_pinjaman']) - $total  ?>
                                        <tr>
                                            <td colspan="3"> Sub Total &nbsp;</td>
                                            <td>&nbsp;</td>
                                            <td style="text-align: right"><?php echo  !empty($totalangsuran) ? rupiah($totalangsuran) : '0,00'?></td>
                                            <td style="text-align: right"><?php echo  !empty($totaldenda) ? rupiah($totaldenda) : '0,00'?></td>
                                            <td style="text-align: right"><?php echo  !empty($totalbiayatagh) ? rupiah($totalbiayatagh) : '0,00'?></td>
                                            <td>&nbsp;</td>
                                            <td style="text-align: right"><?php echo !empty($totaldicount) ? rupiah($totaldicount) : '0,00'?></td>
                                            <td style="text-align: right"><?php echo  !empty($totalbayar) ? rupiah($totalbayar) : '0,00'?></td>
                                            <td colspan="2" align="right">&nbsp;</td>
                                            <td>&nbsp;</td>
                                        </tr>                                       
                                    </table>
                                    
                                </td>
                            </tr>
                             <tr>
                                <td colspan="4"><hr></td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <table width="100%">

                                        <tr align="center">
                                            <td width="50%">Akuntansi</td>
                                            <td widht='50%'>Pimpinan</td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" height="90">&nbsp;</td>
                                        </tr>
                                        <tr align="center">
                                            <td><?php echo $_SESSION[ 'dataLogin' ][ 'realname' ]; ?></td>
                                            <td><?php echo $_SESSION[ 'dataLogin' ][ 'kepala_cabang' ]; ?></td>
                                        </tr >
                                    </table>
                                </td>
                            </tr>                            
                            <tr valign="bottom">
                                <td colspan="4" align="right" height="50"><a  onclick="cetak()" class="btn btn-primary" role="button">Cetak</a></td>
                            </tr>
                        </tbody>
                        <tfoot>
                        </tfoot>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var cetak = function(){
        var params = [
                        'height='+screen.height,
                        'width='+screen.width/2,
                        'fullscreen=yes' // only works in IE, but here for completeness
                    ].join(',');
        window.open('<?php echo URL.'laporan/index/cetakKas/'.$id;?>');// 'toolbar=no, scrollbars=no, resizable=no,fullscreen=1');
    };
</script>