<!-- Main content -->
<section class="content">

    <div class="error-page">
        <h2 class="headline text-yellow"> 500</h2>
        <br/>   
        <div class="error-content">
            <h3><i class="fa fa-warning text-yellow"></i> Oops! Can't Access.</h3>
            <p> 
                We could not Acces the page you were looking for.
                Meanwhile, you may <a href='<?php echo URL?>home'>return to dashboard</a> or try using the search form.
            </p>

        </div><!-- /.error-content -->
    </div><!-- /.error-page -->
</section><!-- /.content -->
