<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    pinjaman
 * @subpackage Form
 * @filesource form-add-pinjaman.phtml
 */
?>


<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/kartupiutang">Kartu Piutang</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>laporan/index/kas">Buku Besar Penerimaan Kas</a>
                </li>
                <li>
                    Buku Besar Piutang
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Cetak Buku Besar Piutang</h3>
                </div>
                <?php if ( !empty( $error ) ): ?>
                    <div class="alert alert-error alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong><i class="icon fa fa-warning"></i> Alert!</strong><br/>
                        <?php echo $error; ?>
                    </div>
                <?php endif; ?>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>laporan/index/cariPiutang" method="post" enctype="multipart/form-data">

                       

                        <div class="form-group">
                            <label for="Nama" class="col-sm-3 control-label">Tanggal</label>
                             <div class="input-group col-sm-3">
                                <input type="text" class="form-control" id="tanggal" placeholder="Tanggal Awal" name="Tanggal" 
                                        required="true">
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="No Polisi" class="col-sm-3 control-label">Sampai</label>
                            <div class="input-group col-sm-3">
                                <input type="text" class="form-control" id="sampai" placeholder="Sampai Tanggal" name="Sampai" 
                                        required="true">
                            </div>
                        </div>   



                        <div class="form-group">
                            <div class="input-group col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-primary">Cetak</button> &nbsp;
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
