<?php

/**
 * MDPU Finance
 * @category   Modules
 * @package    Kendaraan
 * @subpackage Form
 * @filesource form-detail-kendaraan.phtml
 */

?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL?>kendaraan">Data Kendaraan</a>
                </li>
                <li>
                    Detail Kendaraan
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Detail  Kendaraan</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>kendaraan/index/save" method="post" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="nopolisi" class="col-sm-2 control-label">NIK Costumer</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control"  placeholder="NIK Costumer" name="nik_costumer" required="true" readonly="true" value="<?php echo (!empty($data->nik_costumer) ? $data->nik_costumer : null)?>">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="nopolisi" class="col-sm-2 control-label">No Polisi</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control"  placeholder="No Polisi" name="no_polisi" required="true" readonly="true" value="<?php echo (!empty($data->no_polisi) ? $data->no_polisi : null)?>">
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="No BPKB" class="col-sm-2 control-label">No BPKB</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="no_bpkb" placeholder="No BPKB" name="no_bpkb" required="true" readonly="true" value="<?php echo (!empty($data->no_bpkb) ? $data->no_bpkb : null)?>">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Nama BPKB" class="col-sm-2 control-label">Nama BPKB</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="nama_bpkb" placeholder="Nama BPKB" name="nama_bpkb"   required="true" readonly="true" value="<?php echo (!empty($data->nama_bpkb) ? $data->nama_bpkb : null)?>">
                            </div>
                        </div>   
                        
                        
                        <div class="form-group">
                            <label for="Alamat" class="col-sm-2 control-label">Alamat</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat" name="alamat" readonly="true"><?php echo (!empty($data->alamat) ? $data->alamat : null)?></textarea>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Merk / Type" class="col-sm-2 control-label">Merk / Type</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="merk/type" placeholder="Merk / Type" name="merk/type" 
                                       required="true" readonly="true" value="<?php echo (!empty($data->merk) ? $data->merk : null)?>">
                            </div>
                        </div>    
                        
                        <div class="form-group">
                            <label for="No Mesin" class="col-sm-2 control-label">No Mesin</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="no_mesin" placeholder="No Mesin" name="no_mesin" 
                                       required="true" readonly="true" value="<?php echo (!empty($data->no_mesin) ? $data->no_mesin : null)?>">
                            </div>
                        </div>    
                        
                        <div class="form-group">
                            <label for="No Rangka" class="col-sm-2 control-label">No Rangka</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="no_rangka" placeholder="No Rangka" name="no_rangka" 
                                        required="true" readonly="true" value="<?php echo (!empty($data->no_rangka) ? $data->no_rangka : null)?>">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Warna" class="col-sm-2 control-label">Warna</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="warna" placeholder="Warna" name="warna" 
                                        required="true" readonly="true" value="<?php echo (!empty($data->warna) ? $data->warna : null)?>">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Tahun Pembuatan" class="col-sm-2 control-label">Tahun Pembuatan</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="tahun_pembuatan" placeholder="Tahun Pembuatan" name="tahun_pembuatan" 
                                       required="true"readonly="true" value="<?php echo (!empty($data->tahun_pembuatan) ? date('d/m/Y',strtotime($data->tahun_pembuatan)) : null)?>" >
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">Isi Silinder</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="isi_silinder" placeholder="Isi Silinder" name="isi_silinder" 
                                        required="true" readonly="true" value="<?php echo (!empty($data->isi_silinder) ? $data->isi_silinder : null)?>" >
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Tanggal STNK" class="col-sm-2 control-label">Tanggal STNK</label>
                            <div class="col-sm-2" id="sd">
                                <input type="text" class="datepicker form-control input-append date" id="tgl_stnk"  placeholder="Tanggal STNK" name="tgl_stnk" 
                                       required="true" readonly="true" value="<?php echo (!empty($data->tgl_stnk) ? date('d/m/Y',strtotime($data->tgl_stnk)) : null)?>" >
                                <span class="add-on"><i class="icon-th"></i></span>
                            </div>
                        </div>   
                        
                        
                  
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="<?php echo URL?>kendaraan" class="btn btn-primary" role="button">Data Kendaraan</a>               
                                <a href="<?php echo URL.'kendaraan/index/edit/'.$data->id_kendaraan ?>" class="btn btn-primary" role="button">Edit Kendaraan</a>               
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

    