<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Costumer
 * @subpackage Form
 * @filesource form-detail-costumer.phtml
 */
?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>costumer">Data Costumer</a>
                </li>
                <li>
                    Detail Costumer
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Detail Costumer</h3>
                </div>

                <div class="panel-body">

                    <form class="form-horizontal" role="form" action="<?php echo URL ?>costumer/index/save" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="<?php echo URL . 'kendaraan/index/add/' . $data[ 'nik_costumer' ] ?>" class="btn btn-primary" role="button">ADD Kendaraan</a>
                                <a href="<?php echo URL . 'kendaraan/index/byid/' . $data[ 'nik_costumer' ] ?>" class="btn btn-primary" role="button">Data Kendaraan</a>
                                <?php if ( empty( $cekPenjamin ) ) : ?>
                                    <a href="<?php echo URL . 'penjamin/index/add/' . $data[ 'nik_costumer' ] ?>" class="btn btn-primary" role="button">ADD Penjamin</a>
                                <?php elseif ( !empty( $cekPenjamin ) ) : ?>
                                    <a href="<?php echo URL . 'penjamin/index/detail/' . $data[ 'nik_costumer' ] ?>" class="btn btn-primary" role="button">Detail Penjamin</a>
                                <?php endif; ?>
                            </div>
                        </div>
                        <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                            <thead>
                                <tr>
                                    <th class="col-sm-2">Nik Costumer</th>
                                    <th class="col-sm-1">No Polisi</th>
                                    <th class="col-sm-2">No BPKB</th>
                                    <th class="col-sm-2">Merek /Type</th>
            <!--                        <th class="col-sm-2">Tahun Pembuatan</th>-->
                                    <th class="col-sm-3" align="center"><p class="text-justify">Action</p></th>
                            </tr>
                            </thead>
                            <tbody> 
                                <?php $i = 0; ?>  
                                <?php if ( !empty( $data ) )  ?>  
                                <?php foreach ( $data as $val ):$i++; ?>
                                    <tr>

                                        <td class="col-sm-2"><?php echo $val[ 'nik_costumer' ] ?></td>
                                        <td class="col-sm-1"><?php echo $val[ 'no_polisi' ] ?></td>
                                        <td class="col-sm-2"><?php echo $val[ 'no_bpkb' ] ?></td>
                                        <td class="col-sm-2"><?php echo $val[ 'merk' ] ?></td>

                                        <td align="center" class="col-sm-3 small">

                                            <a href="<?php echo URL . 'kendaraan/index/detail/' . $val[ 'no_polisi' ]; ?>" title="Detail"> <i class="fa fa-newspaper-o"></i>&nbsp;Detail</a>
                                                <?php if ( $_SESSION[ 'level' ] === 'superadmin' ): ?>
                                                &nbsp;|&nbsp;
                                                <a href="<?php echo URL . 'kendaraan/index/edit/' . $val[ 'id_kendaraan' ]; ?>"> <i class="fa fa-edit"></i>&nbsp;Edit</a>
                                                &nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                                                <a href="<?php echo URL . 'kendaraan/index/delete/' . $val[ 'no_polisi' ]; ?>"> <i class="fa fa-trash-o"></i>&nbsp;Delete </a>
                                                <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>  

                            </tbody>
                        </table>


                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

