<?php

/**
 * MDPU Finance
 * @category   Modules
 * @package    Cabang
 * @subpackage Form
 * @filesource form-add-cabang.phtml
 */

?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL?>kendaraan">Data Costumer</a>
                </li>
                <li>
                    Input Costumer
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Input Costumer</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>kendaraan/index/save" method="post" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="NIK Costumer" class="col-sm-2 control-label">NIK Costumer</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="nik_costumer" placeholder="Nik Costumer" name="nik_costumer" required="true" readonly="">
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="Nama" class="col-sm-2 control-label">Nama</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="nama" placeholder="Nama" name="nama" required="true">
                            </div>
                        </div>   
                                               
                        
                        <div class="form-group">
                            <label for="Alamat" class="col-sm-2 control-label">Alamat</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat"></textarea>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Merk / Type" class="col-sm-2 control-label">Tempat Lahir</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" placeholder="Tempat Lahir" name="tempat_lahir" 
                                       required="true">
                            </div>
                        </div>    
                        
                        <div class="form-group">
                            <label for="No Mesin" class="col-sm-2 control-label">No Mesin</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="no_mesin" placeholder="No Mesin" name="no_mesin" 
                                        required="true">
                            </div>
                        </div>    
                        
                        <div class="form-group">
                            <label for="No Rangka" class="col-sm-2 control-label">No Rangka</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="no_rangka" placeholder="No Rangka" name="no_rangka" 
                                        required="true">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Warna" class="col-sm-2 control-label">Warna</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="warna" placeholder="Warna" name="warna" 
                                        required="true">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Tahun Pembuatan" class="col-sm-2 control-label">Tahun Pembuatan</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="tahun_pembuatan" placeholder="Tahun Pembuatan" name="tahun_pembuatan" 
                                        required="true">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">Isi Silinder</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control" id="isi_silinder" placeholder="Isi Silinder" name="isi_silinder" 
                                        required="true">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Tanggal STNK" class="col-sm-2 control-label">Tanggal STNK</label>
                            <div class="col-sm-2" id="sd">
                                <input type="text" class="datepicker form-control input-append date" id="tgl_stnk" data-date-format="yyyy/mm/dd" placeholder="Tanggal STNK" name="tgl_stnk" 
                                       required="true">
                                <span class="add-on"><i class="icon-th"></i></span>
                            </div>
                        </div>   
                        
                        
                  
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="reset" class="btn btn-default">Cancel</button>
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

    