
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
           <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
				<li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>costumer/index/all">Data All Costumer</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>costumer/index">Data Costumer</a>
                </li>
                
                <li>
                    Cetak Data Costumer
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Cetak Data Costumer</h3>
                </div>
                
                <div class="panel-body">
                    <br/>
                    <table width="100%" align="center"  border="0"  >
                        <thead>
                            <tr>
                                <td rowspan="1" align="center" width="20%">
                                    <img src="<?php echo URL?>public/images/logo.png" height="80">
                                </td>
                                <td  align="left" colspan="3"><strong>PT MITRA DANA PUTRA UTAMA FINANCE LAMPUNG</strong><br/>Data Costumer <br/>Pertanggal <?php echo date('Y/m/d');?></td>
                            </tr>
                           

                        </thead>
                       
                        <tfoot>
                            <tr>
                                <td colspan="4"><hr></td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <table width="100%">
                                        <tr>
                                        <td>Nik Costumer</td>
										<td>Nama</td>
										<td>Alamat</td>
										<td>Tempat Tgl Lahir</td>
										<td>Nama Ibu</td>
										<td>Jenis Kelamin</td>
										<td>Agama</td>
										<td>Status</td>
										<td>Pekerjaan</td>
										<td>Hp</td>
										<td>Telpon</td>
										<td>Npwp</td>
										<td>Penghasilan</td>
										<td>Jumlah Tanggungan</td>
									
                                        </tr>
                                        
                                       
											<?php if(!empty($data)):?>
											<?php foreach($data as $val):?>
												 <tr>
												<td><?php echo $val['nik_costumer'];?></td>
												<td><?php echo $val['nama'];?></td>
												<td><?php echo $val['alamat'];?></td>
												<td><?php echo $val['tempat_lahir'].','.$val['tanggal_lahir'];?></td>
												<td><?php echo $val['nama_ibu'];?></td>
												<td><?php echo $val['jenis_kelamin'];?></td>
												<td><?php echo $val['agama'];?></td>
												<td><?php echo $val['status'];?></td>
												<td><?php echo $val['pekerjaan'];?></td>
													<td><?php echo $val['hp'];?></td>
														<td><?php echo $val['telpon'];?></td>
															<td><?php echo $val['npwp'];?></td>
															<td><?php echo $val['penghasilan_perbulan'];?></td>
															<td><?php echo $val['jumlah_tanggungan'];?></td>
											<?php endforeach; ?>
											<?php endif;?>
                                        </tr>   
                                       
                                    </table>
                                </td>
                            </tr>
                             <tr>
                                <td colspan="4"><hr></td>
                            </tr>
                             <!--                           
                            <tr valign="bottom">
                                <td colspan="4" align="right" height="50"><a  onclick="cetak()" class="btn btn-primary" role="button">Cetak</a></td>
                            </tr>-->
                        
                        </tfoot>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var cetak = function(){
        var params = [
                        'height='+screen.height,
                        'width='+screen.width/2,
                        'fullscreen=yes' // only works in IE, but here for completeness
                    ].join(',');
        window.open('<?php echo URL.'laporan/index/cetaKP/'.$dataCetak[0]['no_kontrak'];?>');// 'toolbar=no, scrollbars=no, resizable=no,fullscreen=1');
    };
</script>
