<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Costumer
 * @subpackage View
 * @filesource dataCostumer.phtml
 */
?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa fa-edit active"></i> <a href="<?php echo URL ?>costumer/index/add">Input Costumer</a>
                </li>
                <?php if($_SESSION['level']==='superadmin'):?>
                    <li>
                        <i class="fa fa-table active"></i><a href="<?php echo URL ?>costumer/index/all"> Data All Costumer</a>   
                    </li>
                <?php endif;?>
                <li>
                    <i class="fa fa-table active"></i> Data Costumer   
                </li>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Costumer Cabang , &nbsp;<strong> <?php echo (!empty($data[0]['cabang']) ? $data[0]['cabang'] : null);?></strong></h3>
        </div>
        <div class="box-body" > 
            <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                <thead>
                    <tr>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-2">Alamat</th>
                        <th class="col-sm-2">Jenis Kelamin</th>
                        <th class="col-sm-1">Pekerjaan</th>
                        <th class="col-sm-3" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td><?php echo $val['nik_costumer'] ?></td>
                            <td><?php echo $val['nama'] ?></td>
                            <td><?php echo $val['alamat'] ?></td>
                            <td><?php echo $val['jenis_kelamin'] ?></td>
                            
                            <td><?php echo $val['pekerjaan'] ?></td>

                            <td align="center small">

                                    <a href="<?php echo URL . 'costumer/index/detail/' . $val['nik_costumer']; ?>"> <i class="fa fa-newspaper-o"></i>&nbsp;Detail </a>
                                <?php if($_SESSION['level']==='superadmin'):?>
                                    &nbsp;|&nbsp;
                                   <a href="<?php echo URL . 'costumer/index/edit/' . $val['nik_costumer']; ?>"> <i class="fa fa-edit"></i>&nbsp;Edit </a>
                                    &nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                                   <a href="<?php echo URL . 'costumer/index/delete/' . $val['nik_costumer']; ?>"> <i class="fa fa-trash-o"></i>&nbsp;Delete</a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
            </table>
        </div>
    </div>
</div>