<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Costumer
 * @subpackage View
 * @filesource dataCostumer.phtml
 */
?>

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa fa-table active"></i> <a href="<?php echo URL ?>costumer">Data Costumer</a>
                </li>
                
                    <li>
                        <i class="fa fa-table active"></i><a href="<?php echo URL ?>kendaraan"> Data  Kendaraan</a>   
                    </li>
                
                <li>
                    <i class="fa fa-table active"></i> Data All Kendaraan   
                </li>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Kendaraan All Cabang </h3>
        </div>
        <div class="box-body" > 
            <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                <thead>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-1">No Polisi</th>
                        <th class="col-sm-2">No BPKB</th>
                        <th class="col-sm-1">Merek /Type</th>
                        <th class="col-sm-1">Cabang</th>
                        <th class="col-sm-2" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td class="col-sm-1"><?php echo $i; ?></td>
                            <td class="col-sm-2"><?php echo $val['nik_costumer'] ?></td>
                            <td class="col-sm-1"><?php echo $val['no_polisi'] ?></td>
                            <td class="col-sm-2"><?php echo $val['no_bpkb'] ?></td>
                            <td class="col-sm-1"><?php echo $val['merk'] ?></td>
                            <td class="col-sm-1"><?php echo $val['cabang'] ?></td>
                            <td align="center" class="small small col-sm-2">

                                    <a href="<?php echo URL . 'kendaraan/index/detail/' . $val['no_polisi']; ?>"> <i class="fa fa-newspaper-o"></i>&nbsp;Detail </a>
                                    <?php if($_SESSION['level']==='superadmin'):?>
                                    &nbsp;|&nbsp;
                                   <a href="<?php echo URL . 'kendaraan/index/edit/' . $val['id_kendaraan']; ?>"> <i class="fa fa-edit"></i>&nbsp;Edit </a>
                                    &nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                                   <a href="<?php echo URL . 'kendaraan/index/delete/' . $val['no_polisi']; ?>"> <i class="fa fa-trash-o"></i>&nbsp;Delete </a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
                <tfoot>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-1">No Polisi</th>
                        <th class="col-sm-2">No BPKB</th>
                        <th class="col-sm-1">Merek /Type</th>
                        <th class="col-sm-1">Cabang</th>
                        <th class="col-sm-2" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>