<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Home
 * @subpackage View
 * @filesource index.phtml
 */
?>
<!-- Main content -->

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
    <br/>
    <div class="text-center">
               <h1 class="text-yellow">Welcome to Dashboard MDPU - FINANCE</p></h1>
               <h1 class="text-yellow"><?php echo strtoupper($_SESSION['dataLogin']['level']).'-'.$_SESSION['dataLogin']['cabang']?></h1>
               <img src="<?php echo URL?>public/images/banner.jpg" height="300px" width="800px"class="img-thumbnail">
               
               
    </div>
	 
        </div>
    </div>
</div>
