<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Home
 * @subpackage View
 * @filesource index.phtml
 */
?>
<!-- Main content -->

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
    <br/>
    <h1 class="text-yellow" align="center"> <p align='justify'><img src="<?php echo URL?>public/images/logo.png" height="80">Welcome to Dashboard MDPU - FINANCE</p></h1>
	 
        </div>
    </div>
</div>
