<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Costumer
 * @subpackage View
 * @filesource dataCostumer.phtml
 */
?>

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
              
                <?php if($_SESSION['level']==='superadmin'):?>
                    <li>
                        <i class="fa fa-table active"></i><a href="<?php echo URL ?>pinjaman/index/all"> Data All Pinjaman</a>   
                    </li>
                <?php endif;?>
                <li>
                    <i class="fa fa-table active"></i><a href="<?php echo URL ?>pinjaman/index">Data Pinjaman </a>  
                </li>
                <li>
                        <i class="fa fa-table active"></i> Data Pinjaman By Costumer 
                </li>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Pinjaman Costumer , &nbsp;<strong> <?php echo $data[0]['nama'];?></strong></h3>
        </div>
        <div class="box-body" > 
             <div class="form-group">
                <div class="col-sm-10">
                    <a href="<?php echo URL . 'kendaraan/index/add/'.$data[0]['nik_costumer'] ?>" class="btn btn-primary" role="button">ADD Kendaraan</a>
                    <?php if(!empty($cekKendaraan)):?>
                                <a href="<?php echo URL . 'kendaraan/index/byid/'.$data[0]['nik_costumer'] ?>" class="btn btn-primary" role="button">Data Kendaraan</a>
                    <?php endif;?>
                    <a href="<?php echo URL . 'costumer/index/detail/'.$data[0]['nik_costumer'] ?>" class="btn btn-primary" role="button">Detail Costumer</a>
                    <?php if(empty($cekPenjamin)) :?>
                        <a href="<?php echo URL . 'penjamin/index/add/'.$data[0]['nik_costumer'] ?>" class="btn btn-primary" role="button">ADD Penjamin</a>
                    <?php elseif(!empty($cekPenjamin)) :?>
                        
                        <a href="<?php echo URL . 'penjamin/index/detail/'.$data[0]['nik_costumer'] ?>" class="btn btn-primary" role="button">Detail Penjamin</a>
                    <?php endif;?>
                </div>
            </div>
            <br/><br/>
            <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                <thead>
                    <tr>
                        <th class="col-sm-1">No Contract</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-2">Nilai Pinjaman</th>
                        <th class="col-sm-2">Angsuran / Bulan</th>
                        <th class="col-sm-1">Lama Angsuran</th>
                        <th class="col-sm-1" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td><?php echo $val['no_kontrak'] ?></td>
                            <td><?php echo $val['nik_costumer'] ?></td>
                            <td><?php echo $val['nama'] ?></td>
                            <td style="text-align: right"><?php echo 'Rp.'. rupiah(isFloatNum($val['nilai_pinjaman'])); ?></td>
                            <td style="text-align: right"><?php echo 'Rp.'. rupiah(isFloatNum($val['angsuran_perbulan'])); ?></td>
                            <td><?php echo $val['lama_angsuran'] ?>&nbsp;X</td>

                            <td align="center">
                                <?php if(empty($spb)):?>
                                    <a href="<?php echo URL . 'pinjaman/index/cetakSPB/' . $val['id_pinjaman']; ?>"> <i class="fa fa-edit"></i>Cetak SPB </a>
                                <?php endif;?>
                                <?php if($_SESSION['level']==='superadmin'):?>
                                    &nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'pinjaman/index/edit/' . $val['id_pinjaman']; ?>"> <i class="fa fa-edit"></i>EDIT </a>
                                    &nbsp;&nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'pinjaman/index/delete/' . $val['id_pinjaman']; ?>"> <i class="fa fa-trash-o"></i>DELETE </a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
            </table>
        </div>
    </div>
</div>