<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Costumer
 * @subpackage View
 * @filesource dataCostumer.phtml
 */
?>

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa fa-table active"></i> <a href="<?php echo URL ?>costumer">Data Costumer</a>
                </li>
                <?php if($_SESSION['level']==='superadmin'):?>
                    <li>
                        <i class="fa fa-table active"></i><a href="<?php echo URL ?>pinjaman/index/all"> Data All Pinjaman</a>   
                    </li>
                <?php endif;?>
                <li>
                    <i class="fa fa-table active"></i> Data Pinjaman   
                </li>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Pinjaman Cabang , &nbsp;<strong> <?php echo $cabang->cabang;?></strong></h3>
        </div>
        <div class="box-body" > 
            <table id="example1" class="table table-bordered table-striped" style="overflow-x: scroll;overflow-y: scroll">
                <thead>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">No Contract</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-1">Nilai Pinjaman</th>
                        <th class="col-sm-1">Angsuran / Bulan</th>
                        <th class="col-sm-1">Lama Angsuran</th>
                        <th class="col-sm-3" align="center"><p class="text-justify">Action</p></th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $val['no_kontrak'] ?></td>
                            <td><?php echo $val['nik_costumer'] ?></td>
                            <td><?php echo $val['nama'] ?></td>
                            <td><?php echo 'Rp.'. rupiah($val['nilai_pinjaman']); ?></td>
                            <td><?php echo 'Rp.'. rupiah($val['angsuran_perbulan']) ?></td>
                            <td><?php echo $val['lama_angsuran'] ?>&nbsp;X</td>

                            <td align="center">

                                    <a href="<?php echo URL . 'kendaraan/index/detail/' . $val['no_polisi']; ?>"> <i class="fa fa-edit"></i>DETAIL </a>                              
                                <?php if($_SESSION['level']==='superadmin'):?>
                                    &nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'kendaraan/index/edit/' . $val['no_polisi']; ?>"> <i class="fa fa-edit"></i>EDIT </a>
                                    &nbsp;&nbsp;|| &nbsp; 
                                   <a href="<?php echo URL . 'kendaraan/index/delete/' . $val['no_polisi']; ?>"> <i class="fa fa-trash-o"></i>DELETE </a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
                <tfoot>
                    <tr>
                        <th class="col-sm-1">No</th>
                        <th class="col-sm-2">No Contract</th>
                        <th class="col-sm-2">Nik Costumer</th>
                        <th class="col-sm-2">Nama</th>
                        <th class="col-sm-1">Nilai Pinjaman</th>
                        <th class="col-sm-1">Angsuran / Bulan</th>
                        <th class="col-sm-1">Lama Angsuran</th>
                        <th class="col-sm-3">Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>