<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    User
 * @subpackage Form
 * @filesource form-profile.php
 */
?>

<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    Profile User
                </li>
            </ol>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Profile User Change Password</h3>
                </div>
                <?php if(!empty($msg)):?>
                    <div class="alert alert-error alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong><i class="icon fa fa-warning"></i> Alert!</strong><br/>
                        <?php
                            foreach($msg as $error){
                                echo $error."</br>";
                            }
                        ?>
                    </div>
                <?php endif;?>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="<?php echo URL?>user/index/savenewpassword" role="form" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="Realname" class="col-sm-2 control-label">Old Password</label>
                            <div class="col-sm-3">
                                <input type="password" class="form-control" placeholder="Old Password" name="oldPassword"
                                       required="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="nama" class="col-sm-2 control-label">New Password</label>
                            <div class="col-sm-3">
                                <input type="password" class="form-control" placeholder="New Password" name="newPassword" required="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="nama" class="col-sm-2 control-label">Repeat New Password</label>
                            <div class="col-sm-3">
                                <input type="password" class="form-control" placeholder="Repeat New Password" name="newPassword2" required="true">
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input type="submit" class="btn btn-primary" value="save">
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
