<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    User
 * @subpackage Form
 * @filesource form-user.php
 */
?>



<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>user">Data User</a>
                </li>
                <li>
                    Input User
                </li>
            </ol>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Input User</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>user/index/save" method="post" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="realname" class="col-sm-2 control-label">Realname</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="username" placeholder="Realname" name="realname" required>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="username" class="col-sm-2 control-label">Username</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="username" placeholder="Username" name="Username" required>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="password" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-3">
                                <input type="password" class="form-control" id="password" placeholder="Password" name="Password" required>
                            </div>
                        </div>    

                        <div class="form-group">
                            <label for="level" class="col-sm-2 control-label">Level</label>    
                            <div class="col-sm-3">
                                <select name="level" class="form-control" required="">
                                    <option value="">PILIH</option>
                                    <option value="admin">Administrator</option>
                                    <option value="kasir">Kasir</option>
                                    <option value="pimpinan">Pimpinan</option>
                                    <option value="keuangan">Keuangan</option>
                                </select>

                            </div>
                        </div>    

                        <div class="form-group">
                            <label for="nama" class="col-sm-2 control-label">Cabang</label>
                            <div class="col-sm-3">
                                <!--<input type="text" class="form-control" id="judul" placeholder="Cabang" name="cabang"--> 
                                <!--value =""required>-->
                                <select name='id_cabang' id='cabang' class='form-control' required="">
                                    <option value="">PILIH</option>
                                    <?php foreach ($data as $key => $val): ?>
                                        <option value="<?php echo $val['id_cabang'] ?>"><?php echo '( ' . $val['provinsi'] . ' ) ' . $val['cabang'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>    


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="reset" class="btn btn-default">Cancel</button>
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
