<?php

/**
 * MDPU Finance
 * @category   Modules
 * @package    Penjamin
 * @subpackage Form
 * @filesource form-add-penjamin.phtml
 */

?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL?>costumer">Data Costumer</a>
                </li>
                <li>
                    Input Penjamin
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Input Penjamin</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>penjamin/index/save" method="post" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="NIK Costumer" class="col-sm-2 control-label">NIK Costumer</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="nik_costumer" placeholder="Nik Costumer" name="nik_costumer" value="<?php echo $id?>" required="true" readonly="true" >
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="NIK Costumer" class="col-sm-2 control-label">NIK Penjamin</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="nik_costumer" placeholder="Nik Costumer" name="nik_penjamin" required="true" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Nama" class="col-sm-2 control-label">Nama</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="nama" placeholder="Nama" name="nama" required="true">
                            </div>
                        </div>   
                                               
                        
                        <div class="form-group">
                            <label for="Alamat" class="col-sm-2 control-label">Alamat</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat" name="alamat" required="true"></textarea>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Tempat Lahir" class="col-sm-2 control-label">Tempat Lahir</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" placeholder="Tempat Lahir" name="tempat_lahir" 
                                       required="true">
                            </div>
                        </div>    
                        
                        <div class="form-group">
                            <label for="Tanggal Lahir" class="col-sm-2 control-label">Tanggal Lahir</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="tanggal_lahir" placeholder="Tanggal Lahir" name="tanggal_lahir" 
                                        required="true">
                            </div>
                        </div>    
                        
                         <div class="form-group">
                            <label for="Jenis Kelamin" class="col-sm-2 control-label">Jenis Kelamin</label>
                            <div class="radio  col-sm-3">
                                <label>
                                    <input type="radio" name="jenis_kelamin" id="status" value="Laki-Laki" required="true"> Laki-Laki                       
                                </label>
                                <label>
                                  <input type="radio" name="jenis_kelamin" id="status" value="Peremuan" required="true" >Perempuan                       
                                </label>
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Nama Ibu" class="col-sm-2 control-label">Nama Ibu</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="nama_ibu" placeholder="Nama Ibu" name="nama_ibu" 
                                        required="true">
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Agama" class="col-sm-2 control-label">Agama</label>
                            <div class="col-sm-3">
                                <select name="agama" class="form-control" required="true" id="agama">
                                    <option value="">PILIH</option>
                                    <option value="islam">ISLAM</option>
                                    <option value="kristen">KRISTEN</option>
                                    <option value="katolik">KATOLIK</option>
                                    <option value="hindu">HINDU</option>
                                    <option value="budha">BUDHA</option>
                                </select>
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="status
                                   " class="col-sm-2 control-label">Status</label>
                            <div class="radio  col-sm-4">
                                <label>
                                    <input type="radio" name="status" id="status" value="Menikah" required="true"> Menikah                       
                                </label>
                                <label>
                                  <input type="radio" name="status" id="status" value="Belum Menikah" required="true" >Belum Menikah                       
                                </label>
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">Pekerjaan</label>
                               <div class="col-sm-3">
                                    <input type="text" class="form-control" id="pekerjaan" placeholder="Pekerjaan" name="pekerjaan"  required="true">
                                </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Tanggal STNK" class="col-sm-2 control-label">Alamat Tempat Kerja</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat Tempat Kerja" name="alamat_tempat_kerja" required="true" ></textarea>
                            </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">No HP</label>
                               <div class="col-sm-3">
                                    <input type="text" class="form-control" id="hp" placeholder="No HP" name="hp"  required="true">
                               </div>
                        </div>   
                        
                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">No Telepon</label>
                               <div class="col-sm-3">
                                    <input type="text" class="form-control" id="hp" placeholder="No Telepon" name="telpon"  >
                               </div>
                        </div>   
                        
                        
                  
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="reset" class="btn btn-default">Cancel</button>
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

    