<?php
/**
 * MDPU Finance
 * @category   Modules
 * @package    Penjamin
 * @subpackage Form
 * @filesource form-detail-penjamin.phtml
 */
?>
<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>costumer">Data Costumer</a>
                </li>
                <li>
                    <i class="fa  fa-table"></i> <a href="<?php echo URL ?>penjamin">Data Penjamin</a>
                </li>
                <li>
                    Detail Penjamin
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Form Detail Penjamin</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="<?php echo URL ?>penjamin/index/save" method="post" enctype="multipart/form-data">

                        <div class="form-group">
                            <label for="NIK Costumer" class="col-sm-2 control-label">NIK Costumer</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="nik_costumer" placeholder="Nik Costumer" name="nik_costumer" value="<?php echo (!empty($data->nik_costumer) ? $data->nik_costumer : null) ?>" required="true" readonly="true" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="NIK Costumer" class="col-sm-2 control-label">NIK Penjamin</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="nik_costumer" placeholder="Nik Costumer" name="nik_penjamin" required="true" value="<?php echo (!empty($data->nik_penjamin) ? $data->nik_penjamin : null); ?>" readonly="true">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Nama" class="col-sm-2 control-label">Nama</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="nama" placeholder="Nama" name="nama" value="<?php echo (!empty($data->nama) ? $data->nama : null); ?>"required="true"  readonly="true">
                            </div>
                        </div>   


                        <div class="form-group">
                            <label for="Alamat" class="col-sm-2 control-label">Alamat</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat" name="alamat" required="true" readonly="true"><?php echo (!empty($data->alamat) ? $data->alamat : null); ?>
                                </textarea>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Tempat Lahir" class="col-sm-2 control-label">Tempat Lahir</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" placeholder="Tempat Lahir" name="tempat_lahir" value="<?php echo (!empty($data->tempat_lahir) ? $data->tempat_lahir : null); ?>" 
                                       required="true" readonly="true">
                            </div>
                        </div>    

                        <div class="form-group">
                            <label for="Tanggal Lahir" class="col-sm-2 control-label">Tanggal Lahir</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="tanggal_lahir" placeholder="Tanggal Lahir" name="tanggal_lahir" 
                                       required="true" value="<?php echo (!empty($data->tanggal_lahir) ? $data->tanggal_lahir : null); ?>" readonly="true">
                            </div>
                        </div>    

                        <div class="form-group">
                            <label for="Jenis Kelamin" class="col-sm-2 control-label">Jenis Kelamin</label>
                            <div class="radio  col-sm-2">
                                <label>
                                    <input type="radio" name="jenis_kelamin" id="status" value="pria" required="true" checked> <?php echo $data->jenis_kelamin ?>                    
                                </label>

                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Nama Ibu" class="col-sm-2 control-label">Nama Ibu</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="nama_ibu" placeholder="Nama Ibu" name="nama_ibu" 
                                       required="true" value="<?php echo $data->nama_ibu ?>" readonly>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Agama" class="col-sm-2 control-label">Agama</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="nama_ibu" placeholder="Agama" name="agama" 
                                       required="true" value="<?php echo strtoupper($data->agama) ?>" readonly>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="status
                                   " class="col-sm-2 control-label">Status</label>
                            <div class="radio  col-sm-4">
                                <label>
                                    <input type="radio" name="status" id="status" value="menikah" required="true" checked><?php echo strtoupper($data->status); ?>                     
                                </label>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">Pekerjaan</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="pekerjaan" placeholder="Pekerjaan" name="pekerjaan"  required="true" readonly="" value="<?php echo strtoupper($data->pekerjaan) ?>">
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Tanggal STNK" class="col-sm-2 control-label">Alamat Tempat Kerja</label>
                            <div class="col-sm-5">
                                <textarea class="form-control" cols="100" rows="2" placeholder="Alamat Tempat Kerja" name="alamat_tempat_kerja" required="true"readonly="true" ><?php echo (!empty($data->alamat_tempat_kerja) ? $data->alamat_tempat_kerja : null); ?>     </textarea>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">No HP</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="hp" placeholder="No HP" name="hp"  required="true" value="<?php echo (!empty($data->hp) ? $data->hp : null) ?>" readonly>
                            </div>
                        </div>   

                        <div class="form-group">
                            <label for="Isi Silinder" class="col-sm-2 control-label">No Telepon</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="hp" placeholder="No Telepon" name="telpon" value="<?php echo (!empty($data->telpon) ? $data->telpon : null) ?>" readonly  >
                            </div>
                        </div>   



                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                    <a href="<?php echo URL ?>costumer" class="btn btn-primary" role="button">Data Costumer</a>
                                <?php if ($_SESSION['level'] === 'superadmin'): ?>
                                    <a href="<?php echo URL . 'penjamin/index/edit/' . $data->id_penjamin ?>" class="btn btn-primary" role="button">Edit Penjamin</a>
                                <?php endif; ?>
                            </div>
                        </div>                               
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

