<?php

/**
 * MDPU Finance
 * @category   Modules
 * @package    Cabang
 * @subpackage View
 * @filesource datacabang.phtml
 */

?>




<div class="container-fluid">
    <br/>
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="<?php echo URL ?>">Home</a>
                </li>
                <li>
                    <i class="fa fa-edit "></i> <a href="<?php echo URL ?>cabang/index/add">Input Cabang</a>
                </li>
                <li>
                    <i class="fa fa-table active"></i> Data Cabang   
                </li>

            </ol>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-archive fa-fw"></i> Data Cabang</h3>
        </div>
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>

                        <th class="col-sm-1">No</th>
                        <th class="col-lg-3">Provinsi</th>
                        <th class="col-lg-3">Kota</th>
                        <th class="col-lg-2">Kode Post</th>
                        <th class="col-sm-2" >Action</th>
                    </tr>
                </thead>
                <tbody> 
                    <?php $i = 0; ?>  
                    <?php if (!empty($data))  ?>  
                    <?php foreach ($data as $val):$i++; ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $val['provinsi'] ?></td>
                            <td><?php echo $val['kota'] ?></td>
                            <td><?php echo $val['kode_pos'] ?></td>
                            <td align="center">
                                <a href="<?php echo URL . 'cabang/index/edit/' . $val['id_cabang']; ?>"> <i class="fa fa-edit"></i>EDIT </a>
                                &nbsp;|| &nbsp; 
                                <a href="<?php echo URL . 'cabang/index/delete/' . $val['id_cabang']; ?>"> <i class="fa fa-trash-o"></i>DELETE </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>  

                </tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Provinsi</th>
                        <th>Kota</th>
                        <th>KodePost</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div>