<script type="text/javascript">
    window.print();
    window.onfocus = function(){
        var count =3;
        if(count > 3){
            window.close();
        }
        
    };
</script>
<style>
.kotak {
    width: 5px;
    height: 5px;
    padding: 10px;
    border: 2px solid black;
    margin: 0;
}
.kotak-kecil {
    width: 15px;
    height: 15px;
    padding: 10px;
    border: 1px solid black;
    margin: 0 1% 1% 0;
    display: inline-block;
    /*float: left;*/
}

</style>    
<body style="padding-top: 10px">
                    <br/>
                    <table width="100%" align="center" border="0"  cellspacing="1" cellpading="1">
                        <thead>
                            <tr>
                                <td rowspan="5" align="center" width="20%">
                                    <img src="<?php echo URL ?>public/images/logo.png" height="80">
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3" style="text-align: center ;font-size: 14px"><b>MDPU FINANCE</b></td>
                                <td rowspan="3" style="text-align: center ;font-size: 15px" valign="middle" ><?php echo $dataCetak[ 'no_kwitansi' ] ?></td>
                            </tr>
                            <tr>
                                <td  align="left" colspan="3" style="text-align: center ;font-size: 13px"><strong>(PT MITRA DANA PUTRA UTAMA FINANCE)</strong></td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <table width="100%" border="0" cellspacing="0" cellpading="0">
                                        <tr>
                                            <td style="text-align: center ;font-size: 12px">
                                                Jl Gajah Mada Komplek Duta Merlia Blok D No 3-4-5-6,Jakarta Pusat
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center ;font-size: 12px">
                                                Tel : (62-21)63866017,63866018 (hunting) 6341784, 6341760, 6341752
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center ;font-size: 12px">
                                                6324406, 6324384, Fax(62-21) 6306880, 6307278, 6431752
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3" style="text-align: center">
                                    <table width="100%" boder="0" cellspacing="0" cellpading="0">
                                        <tr>
                                            <td style="text-align: center ;font-size: 13px"><u><b>TANDA TERIMA RESMI</u></b></td>
                                            </tr>
                                            <tr>
                                                <td style="text-align: center ;font-size: 13px"><b>OFFICIAL RECEIPT</b></td>
                                            </tr>
                                    </table>
                                </td>
                                <td rowspan="1">
                                    <table border="0" cellspacing="0" cellpading="0">
                                        <tr>
                                            <td style="text-decoration-line: underline  ;font-size: 12px"><b>Tanggal</b></td>
                                            <td>&nbsp;:&nbsp; </td>
                                            <td style="font-size: 12px"><?php echo date( 'd/m/Y' ); ?></td>
                                        </tr>
                                        <tr>
                                            <td style="font-size: 12px"><b>Date</b></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </table>

                                </td>
                            </tr>                                                       
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="6">
                                    <table width="100%" border="1" style="font-size:11px"  cellspacing="0" cellpading="0">
                                        <tr>
                                            <td colspan="5">    
                                                <table width="100%" border="0" cellspacing="0" cellpading="0" >
                                                    <td width="40%" style="font-size:10px"><u>Telah Terima Dari  </u>:&nbsp;<?php echo $dataCetak['nama'];?><br><i>Recive  From</i></td>
                                                    <td align="right" style="font-size:10px"><u>Kontrak  </u>:&nbsp;&nbsp;<br><i>Contract</i>&nbsp;&nbsp;</td>
                                                    <td colspan="3" width="30%" valign="center">
                                                    <table border="1" width="100%" cellspacing="0" cellpading="0">
                                                            <tr align="center" style="font-size:10px">
                                                                <?php $n_kontrak = explode( '-',$dataCetak['no_kontrak'])?>
                                                                <td width="25%"><?php echo $n_kontrak[0]?></td>
                                                                <td width="20%"><?php echo $n_kontrak[1]?></td>
                                                                <td width="35%"><?php echo $n_kontrak[2]?></td>
                                                                <td width="20%"><?php echo $n_kontrak[3]?></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </table>
                                            </td>   
                                        </tr>
                                        <tr>
                                            <td colspan="3" align="center">
                                                UNTUK PEMBAYARAN / IN PAYMENT OF
                                            </td>
                                            <td colspan="2" align="center"><u>JUMLAH</u><br><i>Amount</i></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" align="center">
                                                <table width="100%" style="font-size: 11px" cellspacing="0" cellpading="0">
                                                    <tr valign="center" >
                                                        <td><u>Pembayaran Bulanan   </u>:<br><i>Monthly Payment</i> </td>
                                                        <td align="left" >.........<?php echo $dataCetak['angsuran_ke']?>.........</td>
                                                        <td><u>Periode   </u>:<br><i>Period</i> </td>
                                                        <td align="left">.......................</td>
                                                        <td><u>Untuk Bulan   </u>:<br><i>For the month of</i> </td>
                                                        <td align="left">........................</td>
                                                    </tr>
                                                </table>
                                            </td>
                                            <td>&nbsp;</td>
                                            <td width="10"></td>
                                        </tr>
                                        <tr style="font-size: 11px">
                                            <td colspan="3" align="left">
                                        <u>Denda Keterlambatan Bulanan  </u>:<br>
                                        <i>Penalty fee for delay payment</i>
                                            </td>
                                            <td style="text-align: right">Rp.<?php echo $dataCetak['jumlah_angsuran']?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" align="center" height="30">
                                                POTONGAN
                                            </td>
                                            <td style="text-align: right">Rp,<?php echo $dataCetak['potongan']?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" align="center" height="30">
                                                DENDA
                                            </td>
                                            <td style="text-align: right">Rp,<?php echo $dataCetak['denda_dibayar']?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" align="center" height="30">
                                                PEMBAYARAN CABANG, <?php echo strtoupper($dataCetak[ 'cabang' ])?>
                                            </td>
                                            <td style="text-align: right">Rp.<?php echo $dataCetak['total_bayar']?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="5">
                                                <table width="100%" style="font-size: 11px" cellspacing="0" cellpading="0">
                                                    <tr >
                                                        <td valign="top" rowspan="2" width="100"><u>Dibayar dengan  </u>:<br>Payment by</td>
                                                        <td width="6">
                                                            <div class="kotak"></div>
                                                        </td>
                                                        <td>&nbsp;&nbsp;&nbsp;&nbsp;<u>Check  </u><br>
                                                            &nbsp;&nbsp;&nbsp;&nbsp;Cheque</td>
                                                        <td>No : .......................</td>
                                                        <td>Bank : .....................</td>
                                                        <td><u>Cabang </u><br><i>Branch</i></td>
                                                        <td>Bank : .....................</td>
                                                    </tr>
                                                    <tr>
                                                        <td width="6">
                                                            <div class="kotak"></div>
                                                        </td>
                                                        <td colspan="5" align="left">&nbsp;&nbsp;&nbsp;&nbsp;<u>Tunai  </u><br>
                                                            &nbsp;&nbsp;&nbsp;&nbsp;Cash</td>
                                                      
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" width="215">
                                                            <p align="justify">
                                                                Apabila Pembayaran dengan Check Bilyet giro,
                                                                pembayaran ini akan di anggap sah apabila Check Bilyet
                                                    <u>Giro tersebut telah ada penetapan diterima oleh bank</u><br>
                                                    <i>If payment is made by cheque, this receipt will be valid
                                                                when the cheque in honoured by bank
                                                            </i>
                                                    </p
                                                        </td>
                                                        <td colspan="4" valign="center">
                                                            <table width="100%" boder="0" cellpading="0" cellspacing="0">
                                                                <tr>
                                                                    <td>&nbsp;&nbsp;</td>
                                                                    <td style="font-size: 9px"><?php echo $_SESSION['dataLogin']['realname']?><br>Kasir/<i>Cashier</i></td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        
                                    </table>
                                </td>
                            </tr>
                            <tr style="font-size:11px">
                                            <td colspan="6">
                                                F105<br>
                                                Asli Costumer Copy I Kasir Copy II Colection
                                            </td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr valign="bottom">
                                <td colspan="6" align="right" height="50"><a  onclick="cetak()" class="btn btn-primary" role="button">Cetak</a></td>
                            </tr>

                        </tfoot>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
</body>
